baseurl = "https://moonagic.com/"
copyright = "All rights reserved"
# disqusshortname = "vjeantet"
hasCJKLanguage = true
languagecode = "en-US"
paginate = 10
pluralizelisttitles = false
rssLimit = 20
summaryLength = 120
# theme = "casper"
title = "雨戈林多"

# [[menu.main]]
# identifier = "blog"
# name = "Blog"
# url = "/"
# weight = -120

# [[menu.main]]
# name = "Github repos"
# url = "https://github.com/moonagic"
# weight = 100

# [[menu.main]]
# name = "Twitter timeline"
# url = "https://twitter.com/vjeantet"
# weight = 101

[params]
author = "月杪"
authorbio = "在大学教过书,做过游戏,iOS应用,虚幻4.只想安静的当一条咸鱼."
authorlocation = "Chongqing, China"
authorwebsite = "https://moonagic.com"
cover = "images/cover.webp"
# customFooterPartial = "netlify.html"
description = "Laziness, Impatience and Hubris. "
# githubName = "moonagic"
googleAnalyticsUserID = "G-CMJWH56447"
hideHUGOSupport = false
logo = "images/avatar.webp"
# twitterName = "moonagic"
hjsExtraLanguages = [
  "objectivec",
  "swift",
  "shell",
  "yaml",
  "c",
  "cpp",
  "go",
  "rust",
  "bash",
]
hjsStyle = "an-old-hope"

[permalinks]
post = "/:slug/"

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
